<a href="https://colab.research.google.com/github/Vaishali19-shinde/my_practice_doc/blob/main/pandas_practice_9_7_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
#pandas - AData Analysis

In [8]:
#in pandas we have 2 data structure
#1.Series -1D data structure (rows)
#2.Data Frame- 2D data structure(column)

#Q.what is different between Seirs and DataFrame??


In [9]:
import pandas as pd
data=[120,30,40,50]
s=pd.Series(data)
s

,0
0,120
1,30
2,40
3,50


In [10]:
s.ndim

1

In [11]:
type(s)

pandas.core.series.Series

In [12]:
#lets create df

In [13]:
df=pd.DataFrame(data)
df

,0
0,120
1,30
2,40
3,50


In [14]:
df.ndim

2

In [15]:
df=pd.DataFrame([[1,2,3,4],[1,2,3,4],[1,2,]])
df

,0,1,2,3
0,1,2,3.0,4.0
1,1,2,3.0,4.0
2,1,2,NaN,NaN


In [16]:
df.ndim

2

In [17]:
type(df)

pandas.core.frame.DataFrame

In [18]:
# Assignemnt:
# Try to create a Series and DataFrame with str, tuple, list[list],list[tuple],Set,dict

In [19]:
path = "https://raw.githubusercontent.com/hakimyameen/Datasets/refs/heads/main/fifa_eda.csv"
df=pd.read_csv(path)
df

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0


In [20]:
#display first 5 records
#df.head() -->default it returns 5 records
df.head()

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0


In [21]:
df.head(3)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0


In [23]:
df[:4]

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0


In [24]:
#load last 3 records

In [26]:
df.tail()

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0


In [27]:
df.tail(3)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0


In [31]:
df[-3:]

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0


In [32]:
#summary
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18207 entries, 0 to 18206
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   ID                        18207 non-null  int64  
 1   Name                      18207 non-null  object 
 2   Age                       18207 non-null  int64  
 3   Nationality               18207 non-null  object 
 4   Overall                   18207 non-null  int64  
 5   Potential                 18207 non-null  int64  
 6   Club                      17966 non-null  object 
 7   Value                     17955 non-null  float64
 8   Wage                      18207 non-null  float64
 9   Preferred Foot            18207 non-null  object 
 10  International Reputation  18159 non-null  float64
 11  Skill Moves               18159 non-null  float64
 12  Position                  18207 non-null  object 
 13  Joined                    18207 non-null  int64  
 14  Contra

In [35]:
#q.how to check missing values
df.isnull()

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
18203,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
18204,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
18205,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False


In [37]:
df.isna().sum()/len(df)*100

,0
ID,0.000000
Name,0.000000
Age,0.000000
Nationality,0.000000
Overall,0.000000
Potential,0.000000
Club,1.323667
Value,1.384083
Wage,0.000000
Preferred Foot,0.000000


In [38]:
df.isna().sum()

,0
ID,0
Name,0
Age,0
Nationality,0
Overall,0
Potential,0
Club,241
Value,252
Wage,0
Preferred Foot,0


In [39]:
df.shape

(18207, 18)

In [41]:
18207-17907

300

In [45]:
#lets drop the NAN
df.dropna().shape

(17907, 18)

In [46]:
df.dropna(inplace=True)

In [49]:
#check missing values after dropna
df.isna().sum()

,0
ID,0
Name,0
Age,0
Nationality,0
Overall,0
Potential,0
Club,0
Value,0
Wage,0
Preferred Foot,0


In [50]:
import numpy as np

a=np.array([10,200,300,400])
a

array([ 10, 200, 300, 400])

In [51]:
a=a+100

In [52]:
a

array([110, 300, 400, 500])

In [54]:
b=np.array([2,23,45,np.nan])
b

array([ 2., 23., 45., nan])

In [55]:
b.mean()

np.float64(nan)

In [57]:
#drop column
df.columns

Index(['ID', 'Name', 'Age', 'Nationality', 'Overall', 'Potential', 'Club',
       'Value', 'Wage', 'Preferred Foot', 'International Reputation',
       'Skill Moves', 'Position', 'Joined', 'Contract Valid Until', 'Height',
       'Weight', 'Release Clause'],
      dtype='object')

In [60]:
df.columns

sss

Index(['ID', 'Name', 'Age', 'Nationality', 'Overall', 'Potential', 'Club',
       'Value', 'Wage', 'Preferred Foot', 'International Reputation',
       'Skill Moves', 'Position', 'Joined', 'Contract Valid Until', 'Height',
       'Weight', 'Release Clause'],
      dtype='object')

In [61]:
df.drop(columns=['ID'],inplace=True)

In [63]:
df.columns

Index(['Name', 'Age', 'Nationality', 'Overall', 'Potential', 'Club', 'Value',
       'Wage', 'Preferred Foot', 'International Reputation', 'Skill Moves',
       'Position', 'Joined', 'Contract Valid Until', 'Height', 'Weight',
       'Release Clause'],
      dtype='object')

In [63]:
 #assignment:  convert space to _
# ex. Preferred Foot --> Preferred_Foot

In [64]:
df.columns.str.replace(' ', '_')
#df.columns = df.columns.str.replace(' ', '_')

Index(['Name', 'Age', 'Nationality', 'Overall', 'Potential', 'Club', 'Value',
       'Wage', 'Preferred_Foot', 'International_Reputation', 'Skill_Moves',
       'Position', 'Joined', 'Contract_Valid_Until', 'Height', 'Weight',
       'Release_Clause'],
      dtype='object')

In [65]:
# Assignemnt:
# Try to create a Series and DataFrame with str, tuple, list[list],list[tuple],Set,dict

In [66]:
#Series string
s=pd.Series(['vaiashali','varsha','pooja','payal'])
s



,0
0,vaiashali
1,varsha
2,pooja
3,payal


In [67]:
df=pd.DataFrame({ 'name':['vaishali','varsha','pooja'],
                  'city':['mumbai','bangolre','sangli']
                })
df

,name,city
0,vaishali,mumbai
1,varsha,bangolre
2,pooja,sangli


In [70]:
#Series tuple
tuple1=(12,33,44,55)
s=pd.Series(tuple1)
s

,0
0,12
1,33
2,44
3,55


In [77]:
#DataFrame tuple
tuple1=[('vaishali',29,'mumbai'),('varsha',22,'pune')]
df=pd.DataFrame(tuple1,columns=['name','age','city'])
df

,name,age,city
0,vaishali,29,mumbai
1,varsha,22,pune


In [79]:
#DataFrame list[list]

data=[['vaishali',29,'mumbai'],
      ['varsha',22,'pune'],
       ['pooja',12,'sangli']]
data


[['vaishali', 29, 'mumbai'], ['varsha', 22, 'pune'], ['pooja', 12, 'sangli']]

In [83]:
df=pd.DataFrame(data,columns=('Name','Age','City'))
df

,Name,Age,City
0,vaishali,29,mumbai
1,varsha,22,pune
2,pooja,12,sangli


In [85]:
#Series list[list]

list1=[12,33,22,11]
s=pd.DataFrame(list1)
s

,0
0,12
1,33
2,22
3,11


In [88]:
#DataFrame list[tuple]
# Sample list of tuples

data_tuples = [
    ('varsha', 25, 'pune'),
    ('vaishali', 30, 'mumbai'),
    ('pooja', 35, 'sangli')
]
df = pd.DataFrame(data_tuples, columns=['Name', 'Age', 'City'])
df



,Name,Age,City
0,varsha,25,pune
1,vaishali,30,mumbai
2,pooja,35,sangli


In [91]:
#Series list[tuple]
data_tuples = [
    ('varsha'),
    ('vaishali'),
    ('pooja')]
s=pd.Series(data_tuples)
s


,0
0,varsha
1,vaishali
2,pooja


In [96]:
#Series with set
set1={"apple","banana","orange"}
s=pd.Series(list(set1))
s



,0
0,orange
1,banana
2,apple


In [97]:
#DataFrame with set
data = {
    'Category': ['A', 'B'],
    'Tags': [{'promo', 'active'}, {'expired', 'archived'}]
}

df = pd.DataFrame(data)
df


,Category,Tags
0,A,"{promo, active}"
1,B,"{expired, archived}"


In [98]:
#series with dictionay
data_dict = {'Apple': 100, 'Banana': 150, 'Cherry': 200}

# 2. Convert to a Pandas Series
s = pd.Series(data_dict)

s


,0
Apple,100
Banana,150
Cherry,200


In [100]:
#DataFrame with dictionary
data = {
    'Name': ['vaishali', 'varshaa', 'pooja'],
    'Age': [25, 30, 35],
    'City': ['sangli', 'pune', 'sangli']
}

df = pd.DataFrame(data)
df

,Name,Age,City
0,vaishali,25,sangli
1,varshaa,30,pune
2,pooja,35,sangli
